### ISSUE TITLE
Issue with imports from 'kysely/helpers/mysql'

### ISSUE THREAD

**Issue by koskimas** [wirekang/kysely-playground#10]
Hey!

I stumbled into [this issue](https://kyse.link/?p=s&i=FQAvc3eZKyph3mt2wATD)

The error usually means that there are two copies of Kysely. The `SelectQueryBuilder` type imported in the `kysely/helpers/mysql` file comes from a different copy of Kysely than the one passed to the `jsonArrayFrom` in the playground.

Thanks again for maintaining this awesome project!

**Comment by wirekang** [comment]
I'm trying to figure out how to fix this issue but it seems impossible.
"kysely" and "kysely/helpers/*" share the type definition files in `node_modules/kysely/dist/**/*.d.ts` but playground uses bundled type definitions files. Maybe I could use type files as-is without bundling, but it will occurs too many http requests. Disabling ts(2345) is improper too since it's quite broad type error.

https://github.com/wirekang/kysely-playground/blob/47b236843796bc355823f01390135c71c59d3aa0/src/generated/types/kysely_0.25.0.d.ts#L13903


https://github.com/wirekang/kysely-playground/blob/47b236843796bc355823f01390135c71c59d3aa0/src/generated/types/kysely_0.25.0_helpers_mysql.d.ts#L11435

**Comment by wirekang** [comment]
I replaced the type definition `(expr: SelectQueryBuilder)` with `(expr: Expression)` as a temporary solution.

**Comment by koskimas** [comment]
Since 0.26.1, `SelectQueryBuilder` has been an interface and this problem should no longer occur.

**Comment by wirekang** [comment]
You probably mean `0.26.2` :)

**Comment by wirekang** [comment]
## SumUp

Until `0.26.2`,  hacky replacement (`expr: SelectQueryBuilder<any, any, O>` -> `expr: Expression<O>`) will be applied to `helpers/mysql`.

**Comment by koskimas** [comment]
> You probably mean `0.26.2` :)

Yeah, probably 😅
